// routes.js
export const FriendlyRoutes = {
  INTRO: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  HOME: "/home",
  PLANETS: "/planets",
  FAVOURITE: "/favourit",
  ANIMATION: "/animation",
  EARTH_MOON: "/moonanimation",
  SOLAR_SYSTEM: "/Solarsystem",
  COMPARE_PLANETS: "/comparePlanets",
  COMPARE_RESULT: "/compare-result",
  GALAXIES: "/discover-galaxies",
  GALAXY_DETAILS: "/galaxy-details/:id",
  SATELLITES: "/satellites",
  SATELLITE_DETAILS: "/satellites/:id",
  STARS: "/stars",
  STAR_DETAILS: "/star/:id",
  QUIZ: "/quiz",
  QUIZ_LEVEL: "/quiz/level",
  QUIZ_RESULT: "/quizResult",
  SETTINGS: "/settings",
  UPDATE_PROFILE: "/settings/profile",
  EDIT_PASSWORD: "/settings/edit-password",
  DELETE_ACCOUNT: "/settings/delete-account",
  ABOUT_US: "/settings/about-us",
  PROFILE: "/profile",
};

// encoded URLs visible in browser
export const EncodedRoutes = {
  "/": "/a0",
  "/login": "/b1",
  "/signup": "/c2",
  "/home": "/d3",
  "/planets": "/e4",
  "/favourit": "/f5",
  "/animation": "/g6",
  "/moonanimation": "/h7",
  "/Solarsystem": "/i8",
  "/comparePlanets": "/j9",
  "/compare-result": "/k10",
  "/discover-galaxies": "/l11",
  "/galaxy-details/:id": "/m12/:id",
  "/satellites": "/n13",
  "/satellites/:id": "/o14/:id",
  "/stars": "/p15",
  "/star/:id": "/q16/:id",
  "/quiz": "/r17",
  "/quiz/level": "/s18",
  "/quizResult": "/t19",
  "/settings": "/u20",
  "/settings/profile": "/v21",
  "/settings/edit-password": "/w22",
  "/settings/delete-account": "/x23",
  "/settings/about-us": "/y24",
  "/profile": "/z25",
};
